workflows:
  - name: checks
    step_customizations:
      - action: INSERT_AFTER
        job: lint-code
        step_id: check-out-repository
        content:
          - name: Free Disk Space
            id: free-disk-space
            uses: ./.github/actions/free-diskspace

      - action: INSERT_AFTER
        job: lint-typing
        step_id: check-out-repository
        content:
          - name: Free Disk Space
            id: free-disk-space
            uses: ./.github/actions/free-diskspace

      - action: INSERT_AFTER
        job: check-format
        step_id: check-out-repository
        content:
          - name: Free Disk Space
            id: free-disk-space
            uses: ./.github/actions/free-diskspace

      - action: INSERT_AFTER
        job: check-format
        step_id: check-format
        content:
          - name: Check create_script
            id: check-create-script
            run: poetry run -- nox -s create_script:updated

      - action: INSERT_AFTER
        job: build-package
        step_id: build-package
        content:
          - name: Test pip install
            id: test-pip-install
            run: pip install dist/*.whl --extra-index-url https://download.pytorch.org/whl/cpu

  - name: fast-tests
    step_customizations:
      - action: INSERT_AFTER
        job: run-unit-tests
        step_id: check-out-repository
        content:
          - name: Free Disk Space
            id: free-disk-space
            uses: ./.github/actions/free-diskspace
