version: 0.2

batch:
  fast-fail: false
  build-graph:
    - identifier: without_db_tests
      env:
        compute-type: BUILD_GENERAL1_MEDIUM
        privileged-mode: true
      buildspec: ./buildspec_without_db.yml
    #todo reactivate once saas api back to working
    #- identifier: saas_tests
    #  env:
    #    compute-type: BUILD_GENERAL1_MEDIUM
    #    privileged-mode: true
    #  buildspec: ./buildspec_saas.yml
    - identifier: onprem_tests
      env:
        compute-type: BUILD_GENERAL1_LARGE
        privileged-mode: true
      buildspec: ./buildspec_onprem.yml
