version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - curl -sSL https://install.python-poetry.org | python3 -
      - export PATH=$PATH:$HOME/.local/bin
      - poetry env use $(command -v "python3.8")
      - poetry --version
      - poetry install
      - poetry build
      - pip install dist/*.whl
  build:
    commands:
      - poetry run nox -s unit_tests
      - systemctl status docker
      - systemctl start docker
      - poetry run nox -s start_database
      - poetry run nox -s integration_tests
