"""Configuration for nox based task runner"""

from __future__ import annotations

from pathlib import Path

from exasol.toolbox.config import BaseConfig
from pydantic import computed_field


class Config(BaseConfig):
    @computed_field  # type: ignore[misc]
    @property
    def source_code_path(self) -> Path:
        """
        Path to the source code of the project.

        In transformers-extension, this needs to be overridden due to a custom directory
        setup. This will be addressed in:
            https://github.com/exasol/transformers-extension/issues/365
        """
        return self.root_path / self.project_name

    @computed_field  # type: ignore[misc]
    @property
    def version_filepath(self) -> Path:
        """
        Path to the ``version.py`` file included in the project. This is an
        autogenerated file which contains the version of the code. It is maintained by
        the nox sessions ``version:check`` and ``release:prepare``.

         In transformers-extension, this needs to be overridden due to a custom directory
        setup & custom `version.py` location. This will be addressed in:
            https://github.com/exasol/transformers-extension/issues/366
        """
        return self.root_path / "version.py"


PROJECT_CONFIG = Config(
    root_path=Path(__file__).parent,
    project_name="exasol_transformers_extension",
    python_versions=("3.10", "3.11", "3.12", "3.13", "3.14"),
    exasol_versions=("7.1.9",),
)
