"""Configuration for nox based task runner"""

from __future__ import annotations

from pathlib import Path

from exasol.toolbox.config import BaseConfig
from pydantic import computed_field


class Config(BaseConfig):
    python_version_for_slow_checks: str = "3.12"

    @computed_field  # type: ignore[misc]
    @property
    def onprem_integration_test_files(self) -> list[str]:
        """Returns sorted root-relative on-prem integration test file paths."""
        test_directory = self.root_path / "test/integration_tests/with_db"
        return sorted(
            test_file.relative_to(self.root_path).as_posix()
            for test_file in test_directory.rglob("test_*.py")
        )

    @computed_field  # type: ignore[misc]
    @property
    def has_documentation(self) -> bool:
        """
        Indicates that the project serves Sphinx-based documentation. With a few
        exceptions, this should be the case for most projects.

        This will be remedied in:
           https://github.com/exasol/transformers-extension/issues/298
        """
        return False

    @computed_field  # type: ignore[misc]
    @property
    def source_code_path(self) -> Path:
        """
        Path to the source code of the project.

        In transformers-extension, this needs to be overridden due to a custom directory
        setup. This will be addressed in:
            https://github.com/exasol/transformers-extension/issues/365
        """
        return self.root_path / self.project_name

    @computed_field  # type: ignore[misc]
    @property
    def version_filepath(self) -> Path:
        """
        Path to the ``version.py`` file included in the project. This is an
        autogenerated file which contains the version of the code. It is maintained by
        the nox sessions ``version:check`` and ``release:prepare``.

         In transformers-extension, this needs to be overridden due to a custom directory
        setup & custom `version.py` location. This will be addressed in:
            https://github.com/exasol/transformers-extension/issues/366
        """
        return self.root_path / "version.py"


PROJECT_CONFIG = Config(
    root_path=Path(__file__).parent,
    project_name="exasol_transformers_extension",
    python_versions=("3.10", "3.11", "3.12", "3.13"),
    exasol_versions=("7.1.9",),
)
