name: 'Run test'
description: 'This composite action runs the test'
runs:
  using: "composite"
  steps:
    - name: Build Poetry
      run: poetry build
      shell: bash

    - name: Run Python unit test
      run: poetry run nox -s unit
      shell: bash
