name: 'Run tests'
description: 'This composite action runs the tests'
runs:
  using: "composite"
  steps:
    - name: Build Poetry
      run: poetry build
      shell: bash

    - name: Run Python unit tests
      run: poetry run nox -s test:unit
      shell: bash
