name: Build and test project

on: [ push ]

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        testbeds:
          - tests/deployment_tests/test_language_container_deployer.py
          - tests/deployment_tests/test_language_container_deployer_cli.py
          - tests/deployment_tests/test_scripts_* tests/unit_tests/
          - tests/integration_tests/test_model_downloader_udf_script.py
          - tests/integration_tests/test_model_downloader_udf_implementation.py tests/integration_tests/test_download_pretrained_model.py
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.4
      - name: Install Poetry
        run: poetry install
      - name: Build Poetry
        run: poetry build
      - name: Install project whl
        run: pip install dist/*.whl

      - name: Build language container
        run: ./build_language_container.sh

      - name: Start test environment
        run: bash ./scripts/start_integration_test_environment.sh

      - name: Run Python tests
        run: poetry run pytest ${{ matrix['testbeds'] }}
