name: Build and test project

on: [ push ]

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.4
      - name: Install Poetry
        run: poetry install
      - name: Build Poetry
        run: poetry build
      - name: Install project whl
        run: pip install dist/*.whl

      - name: A workaround to increase available disk size
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Start test environment
        run: bash ./scripts/start_integration_test_environment.sh

      - name: Run Python tests
        run: poetry run pytest tests
