name: Build and test project

on: [ push ]

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.1.4
        with:
          poetry-version: 1.2.2
      - name: Install Poetry
        run: poetry install
      - name: Build Poetry
        run: poetry build
      - name: Install project whl
        run: pip install dist/*.whl

      - name: Start test environment
        run: bash ./scripts/start_integration_test_environment.sh

      - name: Run Python tests
        run: poetry run pytest tests
