name: Build project and run unit test

on: [ push ]

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          large-packages: false
      - name: Free disk space by removing large directories
        run: |
          sudo rm -rf /usr/local/graalvm/
          sudo rm -rf /usr/local/.ghcup/
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/local/share/chromium
          sudo rm -rf /usr/local/lib/node_modules
          sudo rm -rf /opt/ghc

      - name: Setup Python & Poetry Environment
        uses: ./.github/actions/prepare_poetry_env
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run unit tests
        uses: ./.github/actions/run_unit_tests
        
  test_pip_install:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python & Poetry Environment
        uses: ./.github/actions/prepare_poetry_env
        with:
          python-version: ${{ matrix.python-version }}

      - name: Test pip install
        uses: ./.github/actions/test_pip_install


      - name: Poetry run pytest integration tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ROLE: ${{ secrets.AWS_ROLE }}
          AWS_DEFAULT_REGION: "eu-central-1"
          SAAS_HOST: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_HOST }}
          SAAS_ACCOUNT_ID: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_ACCOUNT_ID }}
          SAAS_PAT: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_PAT }}
        run: poetry run pytest tests
