name: Build and test project

on: [ push ]

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          large-packages: false
      - name: Free disk space by removing large directories
        run: |
          sudo rm -rf /usr/local/graalvm/
          sudo rm -rf /usr/local/.ghcup/
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/local/share/chromium
          sudo rm -rf /usr/local/lib/node_modules
          sudo rm -rf /opt/ghc

      - uses: ./.github/workflows/action.yml
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build Poetry
        run: poetry build
      - name: Install project whl
        run: pip install dist/*.whl

      - name: Start test environment
        run: bash ./scripts/start_integration_test_environment.sh

      - name: Run Python tests
        run: poetry run pytest tests
