name: Slow-Checks

on:
  workflow_call:
    secrets:
      DOCKER_USER:
        required: true
      DOCKER_PASSWORD:
        required: true
      INTEGRATION_TEAM_SAAS_STAGING_HOST:
        required: true
      INTEGRATION_TEAM_SAAS_STAGING_ACCOUNT_ID:
        required: true
      INTEGRATION_TEAM_SAAS_STAGING_PAT:
        required: true


jobs:
  onprem-integration-tests:
    name: Onprem Integrations
    uses: ./.github/workflows/onprem-integration-tests.yml
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    permissions:
      contents: read

  saas-integration-tests:
    name: Saas Integrations
    uses: ./.github/workflows/saas-integration-tests.yml
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      INTEGRATION_TEAM_SAAS_STAGING_HOST: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_HOST }}
      INTEGRATION_TEAM_SAAS_STAGING_ACCOUNT_ID: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_ACCOUNT_ID }}
      INTEGRATION_TEAM_SAAS_STAGING_PAT: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_PAT }}
    permissions:
      contents: read

  gpu-tests:
    name: Without DB Integrations
    uses: ./.github/workflows/without-db-integration-tests.yml
    secrets: inherit
    permissions:
      contents: read
