name: Without-DB Tests

on:
  workflow_call:
    secrets:
      DOCKER_USER:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build-matrix:
    name: Build Matrix
    uses: ./.github/workflows/matrix.yml
    with:
      matrix_keys_json: '["python_versions"]'
    permissions:
      contents: read

  without-db-tests:
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
    runs-on:
      labels: int-linux-x64-2core-ubuntu24.04-1
    name: Without-DB Tests
    needs: [ build-matrix ]
    steps:
      - name: Check out Repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Free Disk Space
        id: free-disk-space
        uses: ./.github/actions/free-diskspace

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v10
        with:
          python-version: ${{ matrix.python_versions }}
          poetry-version: "2.3.0"

      - name: Run without_db_integration_tests
        env:
          EXASOL_VERSION: ${{ matrix.exasol-version }}
        run: poetry run -- nox -s without_db_integration_tests -- --coverage --db-version "$EXASOL_VERSION"

      - name: Upload Artifacts
        id: upload-artifacts
        uses: actions/upload-artifact@v7
        with:
          name: coverage-python${{ matrix.python_versions }}-exasol${{ matrix.exasol-version }}-slow
          path: .coverage
          include-hidden-files: true
          overwrite: false
